### ISSUE TITLE
不知道你用了没

### ISSUE THREAD

**Issue by HaoweiCh** [faceair/youjumpijump#1]

**Comment by HaoweiCh** [comment]
实际体验效果 不行啊，，大兄弟。方块临近就识别不了。。

**Comment by faceair** [comment]
http://7u2lh1.com1.z0.glb.clouddn.com/IMG_2089.MOV 我自己测试当然是 ok 的… 你可以把你跳错的那一屏截图给我 debug 一下

**Comment by zjl1990518zjl** [comment]
mac上如何运行呢~~我下载了打开直接是文本....

**Comment by faceair** [comment]
@zjl1990518zjl `chmod +x ./jumpAI-darwin-amd64 && ./jumpAI-darwin-amd64`

**Comment by 18o** [comment]
Mac 三星s7 edge 系数1.01 能跳到3000多分

**Comment by faceair** [comment]
下载最新版再试下

**Comment by jivejiang** [comment]
位置计算有偏差，走的不准，不知道是什么原因
