### ISSUE TITLE
刷了几次高分，7000多，10000多都有，好像被拉黑名单了

### ISSUE THREAD

**Issue by 18o** [faceair/youjumpijump#10]
如题，排行榜里出不来了，朋友的排行榜里也没有我了，自己看排行榜是0.

在Android上刷的，难道被拉黑名单了？

**Comment by lyrical1991** [comment]
低调点不行吗

**Comment by Hn1993** [comment]
应该是超过1000就不行了  我一个号1234 一个2974 都不显示排名

**Comment by 18o** [comment]
好惨，新一周了，还是不会进到排行榜里

**Comment by ghost** [comment]
不是吧，我有5k分的在排行榜。
不过今天周一排行榜清空了。

注意下自己编译把sd卡保存截图的文件名改下，否则特征太明显了。

John <notifications@github.com>于2018年1月1日周一 上午8:33写道：

**Comment by AemonChan** [comment]
haha我的也被拉黑了

**Comment by faceair** [comment]
确实有这个问题，我们这种属于物理外挂，跟直接改分的比还属温柔，低调使用就好

**Comment by faceair** [comment]
https://github.com/wangshub/wechat_jump_game/issues/725 https://github.com/faceair/youjumpijump/issues/74 有思路解决了，稍后会参考加上支持
