### ISSUE TITLE
iphone6ps 启动无反应，过会就报错

### ISSUE THREAD

**Issue by Cornflower1991** [faceair/youjumpijump#103]
请输入 WebDriverAgentRunner 监听的 IP 和端口 (例如 192.168.9.94:8100):172.18.212.21：8100
请输入跳跃系数(推荐值 2，可适当调整):2
2018/01/04 17:23:59 现在跳跃系数是 2.000000
2018/01/04 17:23:59 Get http://172.18.212.21%EF%BC%9A8100/screenshot: dial tcp: lookup 172.18.212.21：8100: no such host: goroutine 1 [running]:
runtime/debug.Stack(0xc420053af8, 0x128f740, 0xc420083140)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:28 +0x73
panic(0x128f740, 0xc420083140)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:57 +0xfcb
程序已崩溃，按任意键退出

**Comment by faceair** [comment]
用英文冒号
