### ISSUE TITLE
你们被清零没？

### ISSUE THREAD

**Issue by rootrl** [faceair/youjumpijump#110]
现在不管刷多少分都被清了，不知道腾讯怎么识别的
  设备：macbook + iPhone

**Comment by jiuxuanzhi** [comment]
遇到了，被清零了，而且只能一定时间在本地看得到，朋友微信里看不到

**Comment by weizheng0829** [comment]
现在手动打的都不记录了，退出跳一跳和微信再进就没了

**Comment by faceair** [comment]
到 #74 讨论吧，我的也被反作弊了，手动游戏都无法上传记录。
