### ISSUE TITLE
图片解码失败

### ISSUE THREAD

**Issue by iokyouok** [faceair/youjumpijump#112]
下了IOS版本最新的执行程序，6S，10.3版本
debugger 目录下只有一句话：
2018/01/07 10:57:37 图片解码失败，请参考 https://github.com/faceair/youjumpijump/issues/41

而且当前文件夹下也没有生成截图图片

**Comment by faceair** [comment]
直接用浏览器访问 `http://你的 wda runner IP 端口/screenshot` 把网页里的数据打包给我看看

**Comment by iokyouok** [comment]
刚自己解决了，之前WDA打出的IP地址和端口是192.168.1.XX，我直接按这个地址会报超时，然后我试了127.0.0.1:8100，就出现刚才那个图片解码失败；然后我重启了WDA，这次又打出了localhost:8100，然后我用这个 localhost 成功运行了！
感谢！
但是奇怪的是跳跃系数我设置从1.5到2.04都试了，，感觉跳起来不靠谱啊，一会就挂了，最高才36分，，是不是哪里不对？我的是6S。
{
  "value" : {
    "state" : "success",
    "os" : {
      "name" : "iOS",
      "version" : "10.3.2"
    },
    "ios" : {
      "simulatorVersion" : "10.3.2",
      "ip" : null
    },
    "build" : {
      "time" : "Jan  6 2018 23:27:41"
    }
  },
  "sessionId" : "82E1BB41-3E61-4115-BAA7-F7157FE731F4",
  "status" : 0
}

**Comment by faceair** [comment]
不准的问题可以附上 debugger 目录。你手机运行 wda runner 的时候有卡顿么？

**Comment by iokyouok** [comment]
[patch_debugger.tar.gz](https://github.com/faceair/youjumpijump/files/1609462/patch_debugger.tar.gz)
不卡的。刚跳了几步就挂了，附近你帮忙看一下

**Comment by faceair** [comment]
看这里的截图位置都太靠前了，有的方块都还没掉下来，有的白圈动画还没走完。现在程序中等待的时间是 1.2s，已经不短了。至于为啥会这样，只能猜测是卡顿引起的了..

**Comment by iokyouok** [comment]
呃。。我从手机上看没有卡的感觉，，我看看能不能把时间改成2S再试试。

**Comment by iokyouok** [comment]
这个python的没搞过，要怎么编译？

**Comment by faceair** [comment]
安装 Golang，设置 GOPATH 环境变量，将本仓库代码放到 $GOPATH/src/github.com/faceair 目录下。进到仓库目录 `go build -o youjumpijump-ios ios/main.go`

**Comment by iokyouok** [comment]
呃。 go 语言么，我研究一下，多谢

**Comment by iokyouok** [comment]
jump "github.com/faceair/youjumpijump"

这一句要改成什么？

**Comment by faceair** [comment]
将代码放到 $GOPATH/src/github.com/faceair 目录下后不需要改

**Comment by iokyouok** [comment]
噢。我试一下把代码放到这个目录

**Comment by iokyouok** [comment]
报重复包含了。。代码路径：/usr/local/Cellar/go/1.9.2/libexec/src/github.com/faceair/youjumpijump

$ go build -o youjumpijump-ios ios/main.go
import cycle not allowed
package main
	imports bytes
	imports errors
	imports runtime
	imports runtime/internal/atomic
	imports unsafe
	imports runtime
import cycle not allowed
package main
	imports github.com/faceair/youjumpijump
	imports net/http
	imports crypto/tls
	imports crypto/x509
	imports net
	imports runtime/cgo
	imports runtime/cgo

**Comment by faceair** [comment]
GOPATH 不是 GOROOT
