### ISSUE TITLE
可以把文件push到手机里 但是有问题

### ISSUE THREAD

**Issue by UsingMisz** [faceair/youjumpijump#118]
反馈请将 debugger 目录打包附上，Android 端可以通过 `adb pull /data/local/tmp/debugger` 拉下 debugger 目录。
![image](https://user-images.githubusercontent.com/18585336/34706153-85fd3082-f540-11e7-85da-d2add3b77f21.png)

**Comment by faceair** [comment]
![image](https://user-images.githubusercontent.com/3659110/34706215-1176b728-f541-11e7-9e7b-67aa2ae4dfc9.png)
你 Push 的这是啥

**Comment by UsingMisz** [comment]
不是这个文件吗？ 我好像没有youjumpijump-android这个文件

**Comment by faceair** [comment]
https://github.com/faceair/youjumpijump/releases/tag/1.16 重新下载一份
