### ISSUE TITLE
小米4上无反应，控制台上一直运行着打着log

### ISSUE THREAD

**Issue by fengerwoo** [faceair/youjumpijump#124]
小米4上无反应，控制台上一直运行着打着log

如：

2018/01/11 15:15:39 from:[226 741] to:[528 521] distance:373.64 press:762.22ms
2018/01/11 15:15:44 from:[226 741] to:[528 521] distance:373.64 press:762.22ms
2018/01/11 15:15:49 from:[226 741] to:[528 521] distance:373.64 press:762.22ms
2018/01/11 15:15:54 from:[226 741] to:[528 521] distance:373.64 press:762.22ms

**Comment by fengerwoo** [comment]
已解决，手机没Root，Root后OK

**Comment by faceair** [comment]
跟 root 没关系，可能是开发者选项的安全设置没有开。

**Comment by Thyiad** [comment]
嗯，小米开发者选项打开后，还要打开那个允许模拟点击的选项
