### ISSUE TITLE
小米6，最多只跑到300多点就挂了

### ISSUE THREAD

**Issue by justmd5** [faceair/youjumpijump#14]

**Comment by starriv** [comment]
hhh 我这边也是这样 试了2次 每次不会出300

**Comment by pangys** [comment]
参数调为2.1会不会好些

**Comment by faceair** [comment]
可以试下最新版本，当跳挂的时候把日志打包发上来我看看。

**Comment by caik123** [comment]
我也小米6，跑了3次都是150以下就挂了

**Comment by rj0102** [comment]
参数2.2我能跳到700多

**Comment by mebtte** [comment]
三星s8大概300多就死掉了

**Comment by faceair** [comment]
新增了基于统计的自动系数调节，欢迎再次尝试。

**Comment by slyang520** [comment]
@faceair  更用了你最新代码 掺不忍睹  没有上过50分    系数，2.04，机器魅族pro 6 plus

**Comment by faceair** [comment]
@slyang520 可以把日志打包发给我看下。如果每次都不能跳到最中间的位置，可以自己微调初始系数。自动系数调节需要收集足够的数据才能发挥应有的效果。

**Comment by slyang520** [comment]
[debugger.zip](https://github.com/faceair/youjumpijump/files/1596038/debugger.zip)
@faceair

**Comment by faceair** [comment]
@slyang520 收到，这个看起来是一个识别 bug，我想想办法

**Comment by faceair** [comment]
@slyang520 你的问题合并到 #16 ，其他的没有更多问题这个 issue 我先关了。
