### ISSUE TITLE
有阴影和面积遮挡重叠的情况下失败率好高...

### ISSUE THREAD

**Issue by ghost** [faceair/youjumpijump#16]

**Comment by faceair** [comment]
目前的算法缺陷，正在想新的识别算法。

**Comment by faceair** [comment]
优化了一下右侧有延长的图形中心点识别，欢迎再次帮忙测试。

**Comment by MatrixOne001** [comment]
我刚刷到450分，主动狗带，然后微信就把我成绩给取消了。。。。

**Comment by faceair** [comment]
😕这就不是我们的问题了.. 慎重使用，可能把所有成绩清零...

**Comment by MatrixOne001** [comment]
我就像来个朋友圈前五，泪崩

**Comment by CoMList** [comment]
哈哈，刷低分也不行啊

在 2018-01-05 23:46:51，MatrixOne001 <notifications@github.com> 写道：


我刚刷到450分，主动狗带，然后微信就把我成绩给取消了。。。。

**Comment by faceair** [comment]
反作弊问题可以到 #74 讨论，这个 issue 描述的问题应该解决了，先关了。
