### ISSUE TITLE
红米4（Android6）跳跃1次后失败

### ISSUE THREAD

**Issue by ftitreefly** [faceair/youjumpijump#17]
Good Job!

老人机，红米4尝试跳跃1次后失败，弹错误代码。
分析原因screencap保存jump.png时候主动重命名，类似于jump_154232*****.png，
导致下一次pull文件名jump.png失败，具体原因不详。
临时解决方案，设立临时文件夹：

`path := "/sdcard/jumpdir/"`
`picName := "jump.png"`

`exec.Command("adb", "shell", "rm", "-fr", path + "*").Output()`

`outs,e := exec.Command("adb", "shell", "ls", path).Output()`
`realPicName := outs[0:len(outs)-2]`
`pullpath := path + string(realPicName)`

`exec.Command("adb", "pull", pullpath, picName).Output()`

Debug时候分析，jump.png和jump_15***.png交替出现，可能与创建同名文件覆盖出错相关，建议修复代码。

**Comment by nimohe** [comment]
我这里出现的问题 和你一样
问题：跳一次之后，就程序崩溃，原因是图片拉取不到。
log
```
ai git:(master) ✗ chmod +x ./jumpAI-darwin-amd64 && ./jumpAI-darwin-amd64
请输入跳跃系数(推荐值 2.04):2.04
2017/12/31 11:05:11 from:[224 734] to:[526 495] press:785ms
2017/12/31 11:05:15 ADB 执行失败，请手动执行 "adb pull /sdcard/jump.png ." 看是否有报错: goroutine 1 [running]:
runtime/debug.Stack(0xc42003daa0, 0x10f2500, 0x11342c0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:38 +0x6e
panic(0x10f2500, 0x11342c0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:59 +0x136b
程序已崩溃，请保存日志后按任意键退出
```

后续：
我重启了一下手机，竟然就不报错了。万能的重启。。。

**Comment by faceair** [comment]
ADB 是不太稳定，可以用最新的 Android 版本再试。
