### ISSUE TITLE
小米MIX2，简直乱跳啊，第一下跳老远

### ISSUE THREAD

**Issue by okadwin** [faceair/youjumpijump#18]
小米MIX2，简直乱跳啊，第一下就跳老远。

**Comment by okadwin** [comment]
![image](https://user-images.githubusercontent.com/28555032/34458469-2a17e79a-ee0f-11e7-9d1c-347d4e4f7806.png)
zh鹅掌截图识别出了1246ms，基本上第一条识别出来的距离都在1200-1500ms之间。

**Comment by Markuna** [comment]
同mix，跳跃系数填1.19第一跳可以跳准一点，但灰色圆桌和小鸡会跳在边缘，估计是mix截屏长了点的缘故

**Comment by faceair** [comment]
收到，这张图里的落点判断不太对，我修了下，正在找人验证

**Comment by wenketel** [comment]
![Screenshot_2017-12-31-23-49-32-655_com.tencent.mm.png](https://i.loli.net/2017/12/31/5a4907bf4dd11.png)
mix2系数填2在这里掉了

**Comment by Markuna** [comment]
mix2系数填2.175，可以跳1.3k

**Comment by faceair** [comment]
新增了基于统计的自动系数调节，欢迎尝试。
