### ISSUE TITLE
魅蓝E不可以

### ISSUE THREAD

**Issue by TLastone** [faceair/youjumpijump#19]
请输入跳跃系数(推荐值 2.04):2.04
2017/12/31 10:21:38 unexpected EOF: goroutine 1 [running]:
runtime/debug.Stack(0xc04205baa0, 0x5106c0, 0xc042032070)
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xae
main.main.func1()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:38 +0x75
panic(0x5106c0, 0xc042032070)
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x291
main.main()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:70 +0x1344
程序已崩溃，请保存日志后按任意键退出

**Comment by faceair** [comment]
可以用最新的 Android 版本试试，应该可以绕过 ADB 一些问题。
