### ISSUE TITLE
每次都是跳到同样的坐标

### ISSUE THREAD

**Issue by MuJJus** [faceair/youjumpijump#2]
小米6 1080p用1.35直接飞
0.81刚好第一跳正中间，接下来就一直是这个坐标，gg以后才有改变
miui9 17.12.7 开发版
windows 10
jumpai 1.02 release预编译二进制

请输入跳跃系数:0.81
2017/12/30 10:22:41 from:[343 1118] to:[158 205] press:754ms
2017/12/30 10:22:46 from:[281 1154] to:[158 205] press:775ms
2017/12/30 10:22:50 from:[708 1031] to:[158 205] press:803ms
2017/12/30 10:22:54 from:[343 1118] to:[158 205] press:754ms
2017/12/30 10:22:58 from:[362 1107] to:[158 205] press:749ms
2017/12/30 10:23:03 from:[874 1141] to:[158 205] press:954ms
2017/12/30 10:23:07 from:[726 1079] to:[158 205] press:844ms
2017/12/30 10:23:12 from:[212 814] to:[158 205] press:495ms
2017/12/30 10:23:16 from:[343 1118] to:[158 205] press:754ms
2017/12/30 10:23:20 from:[767 1104] to:[158 205] press:879ms
2017/12/30 10:23:24 from:[208 926] to:[158 205] press:585ms
2017/12/30 10:23:28 from:[343 1118] to:[158 205] press:754ms
2017/12/30 10:23:33 from:[845 1139] to:[158 205] press:939ms
2017/12/30 10:23:37 from:[768 1103] to:[158 205] press:879ms
2017/12/30 10:23:42 from:[744 1089] to:[158 255] press:825ms
2017/12/30 10:23:46 from:[390 1026] to:[158 205] press:691ms
2017/12/30 10:23:50 from:[0 0] to:[158 205] press:209ms
2017/12/30 10:23:54 from:[0 0] to:[596 214] press:512ms
2017/12/30 10:23:58 from:[0 0] to:[596 214] press:512ms

**Comment by ishwy** [comment]
我也是..

**Comment by faceair** [comment]
最新版使用 2.04 再跑跑看

**Comment by MuJJus** [comment]
1.03 版本可以用，2.04 近了点只到 202 分，现在用 2.08 还不错。

**Comment by ishwy** [comment]
只有 1.03版本呀

**Comment by faceair** [comment]
@ishwy 是的 2.04 指的系数
