### ISSUE TITLE
bad mode之后我运行./youjumpijump

### ISSUE THREAD

**Issue by ghost** [faceair/youjumpijump#20]
./youjumpijump: can't execute: Is a directory 安卓版4.3

**Comment by faceair** [comment]
adb shell 连进去执行 `cd /data/local/tmp/ && chmod +x ./youjumpijump || true && ./youjumpijump`

**Comment by faceair** [comment]
怀疑你把 youjumpijump 目录 push 上去了，你确定 push 的是下载的那个单个文件吗？

**Comment by ghost** [comment]
好的，谢谢。 命令：2017/12/31 10:01:56 from:[224 734] to:[526 566] press:704ms 出来了， 但是不跳。。。

**Comment by faceair** [comment]
开发者选项模拟点击开了吗？
