### ISSUE TITLE
bad mode,直接换就说文件没找到

### ISSUE THREAD

**Issue by goodkenneth** [faceair/youjumpijump#21]
19 files pushed. 0 files skipped. 
拷贝的时候，说19个文件都拷贝了。

但运行 的时间 给权限的说 bad mode .
直接 ./youjumpijump 却说not found找不到？

求教。。谢谢

**Comment by faceair** [comment]
`cd /data/local/tmp/ && chmod +x ./youjumpijump || true && ./youjumpijump` 执行这个应该可以避免 bad mode 错误

**Comment by goodkenneth** [comment]
还是 bad mode

**Comment by goodkenneth** [comment]
还是权限错误。。直接运行。就是  Permission denied

**Comment by goodkenneth** [comment]
cd /data/local/tmp/ && chmod 775 ./youjumpijump && ./youjumpijump来启动程序

解决

**Comment by faceair** [comment]
👍
