### ISSUE TITLE
can't execute: Is a directory

### ISSUE THREAD

**Issue by keaituzhe** [faceair/youjumpijump#22]
cd /data/local/tmp/ && chmod +x ./youjumpijump && ./youjumpijump 之后提示can't execute: Is a directory   s8 安卓7.0

**Comment by faceair** [comment]
怀疑你把 youjumpijump 目录 push 上去了，你确定 push 的是下载的那个单个文件吗？

**Comment by keaituzhe** [comment]
谢老铁单文件的   刚才下载的1.1那个包

**Comment by faceair** [comment]
嗯 我更新 readme 写的更清楚些了。
