### ISSUE TITLE
program has crashed

### ISSUE THREAD

**Issue by caik123** [faceair/youjumpijump#25]
![20171231144814](https://user-images.githubusercontent.com/15011350/34459949-850db456-ee3a-11e7-86f4-dde65b89154e.jpg)

**Comment by faceair** [comment]
adb shell 连进去 手动测一下 `/system/bin/sh /system/bin/input swipe 320 410 320 410 300` 看能不能让小人跳起来

**Comment by caik123** [comment]
还是不能跳动，输入这个命令后，终端输出Killed

**Comment by faceair** [comment]
或者执行 `input swipe 320 410 320 410 300`，请附上执行截图

**Comment by caik123** [comment]
![20171231150828](https://user-images.githubusercontent.com/15011350/34460011-87117d26-ee3c-11e7-95a5-0e7a7fd38b3e.jpg)

手机是停留在跳一跳小程序界面，点击了开始

**Comment by faceair** [comment]
执行 `input swipe 320 410 320 410 300` 呢？

**Comment by faceair** [comment]
如果都不能跳起来，可能是手机不支持模拟触摸，或者可以看下开发者选项中是否有模拟触摸的开关是否开启了

**Comment by caik123** [comment]
确实，是模拟触摸没有打开！
打开后就可以了

**Comment by faceair** [comment]
👍
