### ISSUE TITLE
可以设置成在输完2.04后延迟3s运行吗

### ISSUE THREAD

**Issue by ghost** [faceair/youjumpijump#26]
不延迟一下，好尴尬啊🌝🌝🌝
直接秒截屏，就没后续了

![jump 720](https://user-images.githubusercontent.com/34809075/34460037-88b3c106-ee3d-11e7-9cc4-646616a4613c.png)
延迟3s就可以在终端模拟器执行命令，有时间返回微信再截屏，也不怎么影响使用adb的人
还有手机上只能使用终端模拟器才能执行
不能使用neoterm和termux，不然会有权限问题

**Comment by faceair** [comment]
我觉得👌

**Comment by 0312birdzhang** [comment]
你可以`sleep 3 && true && ./youjumpijump`

**Comment by faceair** [comment]
应该不太行 还要输入系数的

**Comment by faceair** [comment]
最后打算让程序支持一个参数即跳跃系数，最后命令就变成 `sleep 3 && true && ./youjumpijump 2.04`

**Comment by ghost** [comment]
![jump 720](https://user-images.githubusercontent.com/34809075/34460900-2b61f972-ee57-11e7-8919-716c2aef6c5b.png)
还是不行啊。。。
和之前一样啊，秒截屏

**Comment by faceair** [comment]
那你 sleep 更久一点 `sleep 20`？

**Comment by faceair** [comment]
Android 版本已经支持参数了，sleep 也没问题，但现在我在所有的 Andoid Terminal 中都遇到了不能截图的问题，具体原因不明

**Comment by ghost** [comment]
![screenshot_2018-01-01-18-32-05-663_com tencent mm](https://user-images.githubusercontent.com/34809075/34467078-4cd96ef2-ef22-11e7-89a3-414d436194e4.png)
我可能用了假辅助🙃🙃🙃
sleep 6 && true && ./youjumpijump1.392

**Comment by faceair** [comment]
如果是报 bug 的话请带日志，开始就没跳准可能是系数问题，可以再看一下我在 readme 里写的描述。
如果确认 android 版本支持了你想要的 feature，那这个 issue 我准备关了。
