### ISSUE TITLE
三星S7EDGE用2560x1440 跟1920x1080都跳不好

### ISSUE THREAD

**Issue by mvpskyo** [faceair/youjumpijump#28]
小人站在绿的的是2560  灰色1440
![2560](https://user-images.githubusercontent.com/33758476/34460228-7637f35c-ee43-11e7-872c-26bcf4c16e59.png)

![1440](https://user-images.githubusercontent.com/33758476/34460236-c5f36098-ee43-11e7-9a1f-51ee3c9a90a8.png)

**Comment by faceair** [comment]
知道为什么了，你这旁边有个白条，目前算法还不能排除这个干扰，我想办法修一下

**Comment by faceair** [comment]
欢迎使用最新版本再测一下
