### ISSUE TITLE
不怎么懂adb,按照说明执行失败了,不知道为什么.

### ISSUE THREAD

**Issue by xghrsw** [faceair/youjumpijump#29]
2017/12/31 08:21:10 now jump ratio is 2.040000
2017/12/31 08:21:14 from:[238 726] to:[510 566] press:643ms
2017/12/31 08:21:15 signal: killed: goroutine 1 [running]:
runtime/debug.Stack(0x1201ad54, 0x115a90, 0x1087a0c0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0x80
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:96 +0x40
panic(0x115a90, 0x1087a0c0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:197 +0xf70

**Comment by faceair** [comment]
开发者选项中模拟触摸的开关是否开启了
