### ISSUE TITLE
一加一手机，跳跃系数0.8，得分个位数

### ISSUE THREAD

**Issue by junbaor** [faceair/youjumpijump#3]
使用的版本是 1.02 windows 版。

得分较少，不知道是我手机问题还是算法问题，又或者微信升级了?
下面这张图跳过了。原谅截图质量不佳。
![](http://ww1.sinaimg.cn/large/d6246196ly1fmym8uo2xdj20fu0rswga.jpg)

图片不显示，点击查看：http://ww1.sinaimg.cn/large/d6246196ly1fmym8uo2xdj20fu0rswga.jpg

**Comment by faceair** [comment]
最新版使用 2.04 系数再跑跑看
