### ISSUE TITLE
小Mi5 执行二进制文件报 语法错误

### ISSUE THREAD

**Issue by maojindao55** [faceair/youjumpijump#30]
root@dior:/data/local/tmp # ./youjumpijump                                     
./youjumpijump[1]: syntax error: '<' unexpected

**Comment by faceair** [comment]
这个错不像是我们的进程报出来的，请确认下你的命令是否正确，以及第二行是什么 @

**Comment by maojindao55** [comment]
二进制文件貌似损坏，我重新下载没问题了，感谢
