### ISSUE TITLE
跳一跳更新了，辅助成功率下降率

### ISSUE THREAD

**Issue by 369779105** [faceair/youjumpijump#31]
反馈一下，31号下午16：00左右游戏更新了，我的1000+记录被清除。
  同时多了很多圆形的的台子，方形的阴影也被做成倾斜的且不是一条直线。
  之前能稳定1000+ 现在只能100+

**Comment by faceair** [comment]
可以把 debugger 目录打包报上来我看一下

**Comment by Jack-data-dev** [comment]
今天上午试了几次，分数最大600+

**Comment by slyang520** [comment]
系数 2.04 最多只能 170  设备Pro 6 PLUS  求个 给力系数

**Comment by Krisloveless** [comment]
@slyang520 我设置的2.3貌似比较给力，你试试看

**Comment by faceair** [comment]
新增了基于统计的系数自动调节，欢迎再次尝试
