### ISSUE TITLE
我觉得大佬你可能理解错了😂😂😂

### ISSUE THREAD

**Issue by ghost** [faceair/youjumpijump#32]
我的意思是在输入数值后，等待3s再执行截屏识别
不是输入数值后截屏，等3s再识别😂😂😂
这张是截屏
![jump 720](https://user-images.githubusercontent.com/34809075/34460813-80143b2c-ee54-11e7-8ab4-bf8864502a49.png)

**Comment by faceair** [comment]
没有理解错 #26 讨论吧
