### ISSUE TITLE
win7 华为荣耀8报错

### ISSUE THREAD

**Issue by ishwy** [faceair/youjumpijump#34]
请输入跳跃系数(推荐值 2.04):2.04
2017/12/31 19:25:57 ADB 执行失败，请手动执行 "adb shell screencap -p /sdcard/jum
p.png" 看是否有报错: goroutine 1 [running]:
runtime/debug.Stack(0xc04205faa0, 0x507e20, 0x54c7f0)
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xae
main.main.func1()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:
38 +0x75
panic(0x507e20, 0x54c7f0)
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x291
main.main()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:
55 +0x1390
程序已崩溃，请保存日志后按任意键退出

**Comment by faceair** [comment]
用最新版
