### ISSUE TITLE
MI 5X 

### ISSUE THREAD

**Issue by Krisloveless** [faceair/youjumpijump#36]
[debug.log](https://github.com/faceair/youjumpijump/files/1595198/debug.log)
![1514727508](https://user-images.githubusercontent.com/15829091/34461933-6af246a2-ee73-11e7-9a92-bd71ca7ddc64.png)

**Comment by faceair** [comment]
开发者选项中的模拟触摸要打开

**Comment by Krisloveless** [comment]
谢谢！
