### ISSUE TITLE
小白问，怎么打包日志，我跳到450挂了

### ISSUE THREAD

**Issue by zhengmin4516** [faceair/youjumpijump#37]
mac系统
![image](https://user-images.githubusercontent.com/12004034/34463048-25ee29fe-ee8c-11e7-8253-1c5c83f18a87.png)
![image](https://user-images.githubusercontent.com/12004034/34463049-283d2142-ee8c-11e7-836d-e889b5f30d15.png)

```
2017/12/31 16:27:33 from:[498 808] to:[242 655] press:685ms
2017/12/31 16:27:39 from:[488 790] to:[271 674] press:565ms
2017/12/31 16:27:45 from:[459 777] to:[306 694] press:400ms
2017/12/31 16:27:51 from:[500 801] to:[268 671] press:611ms
2017/12/31 16:27:56 from:[565 837] to:[198 631] press:967ms
2017/12/31 16:28:03 from:[135 662] to:[198 631] press:161ms
2017/12/31 16:28:08 can't find the starting point，please export the debugger directory
```

红米5 plus，刚开始系数默认只能跳50，2.1 能跳 100 ， 2.2 能跳200，2.3能跳450

**Comment by faceair** [comment]
adb pull /data/local/tmp/debugger

**Comment by faceair** [comment]
新增了自动系数调节，欢迎帮忙测试

**Comment by zhengmin4516** [comment]
@faceair 
![image](https://user-images.githubusercontent.com/12004034/34467105-f9e5d57c-ef22-11e7-981a-1723182db69f.png)
![image](https://user-images.githubusercontent.com/12004034/34467108-fc5db1f8-ef22-11e7-8b5e-229c906eef82.png)
```
2018/01/01 10:33:06 from:[479 785] to:[254 672] press:591ms
2018/01/01 10:33:11 from:[307 776] to:[452 688] press:398ms
2018/01/01 10:33:17 from:[552 850] to:[183 622] press:1019ms
2018/01/01 10:33:23 from:[462 777] to:[274 674] press:503ms
2018/01/01 10:33:29 from:[266 805] to:[496 663] press:635ms
2018/01/01 10:33:35 from:[546 835] to:[195 630] press:955ms
2018/01/01 10:33:41 from:[188 813] to:[544 636] press:934ms
2018/01/01 10:33:47 from:[629 659] to:[675 629] press:129ms
```
18:9的红米5 plus， 2.3的系数，应该是屏幕尺寸的关系

另外，用华为nova2，昨天晚上11点下的程序，2.1的系数，2次都能跳到2000+，然后被我手动终止，经常跳中心点，一次+30，大神66666
