### ISSUE TITLE
这是什么错误呢? 在iphone5se上面

### ISSUE THREAD

**Issue by linkjane** [faceair/youjumpijump#41]
![image](https://user-images.githubusercontent.com/15264018/34465027-73436fbc-eed6-11e7-9b9b-d55844610dda.png)
第一次启动启动就出现这个错误了, 跳跃系数1-3之间都试了还是这个错误,是屏幕分辨率的问题吗?看着像是base64也就是截图发生了错误?

**Comment by faceair** [comment]
#40 似乎是同样的问题，重启下微信或者 wda ？

**Comment by linkjane** [comment]
重启微信或者wda都试过了, 还是不行, 换一台手机就行, 比如iphone6/7 ios11, 那个5se是ios10.1.1系统版本的

**Comment by qfdk** [comment]
重启下微信 看看web 界面可以获取到桌面么 可以获取到桌面 重新开微信 另外我是5S 最高分数是300 基本上是100 就挂 系数测试了2.04 2.0388888 2.038999999 类似于这样的数据 具体没看代码 有几个数值会直接约等于2.04 尴尬

**Comment by zuojinmin** [comment]
5se 会出现这个问题

**Comment by zuojinmin** [comment]
我现在在 看下golang 源码

**Comment by faceair** [comment]
我目前没有时间来析这个问题，各位如果有结论了或者修好了可以再评论一下

**Comment by zuojinmin** [comment]
是 WebDriverAgent 某个图片解析出现了问题

**Comment by zuojinmin** [comment]
9.x 10.x 系统会出现这种问题

**Comment by faceair** [comment]
明白了，感谢排查👍 那这个问题我们这边做不了什么，我先标记成 wontfix 了

**Comment by zuojinmin** [comment]
你看下我fork 的代码有没有问题
