### ISSUE TITLE
iphoneX 乱跳， 试了好多系数

### ISSUE THREAD

**Issue by HockeyWX** [faceair/youjumpijump#42]
RT

**Comment by faceair** [comment]
debugger 目录打包上传下

**Comment by HockeyWX** [comment]
[debugger.zip](https://github.com/faceair/youjumpijump/files/1595606/debugger.zip)

**Comment by faceair** [comment]
里面没图的吗..

**Comment by faceair** [comment]
再跑一遍？

**Comment by HockeyWX** [comment]
我重新跑了一遍，里面就只有一个log文件。

**Comment by HockeyWX** [comment]
是不是iPhoneX的分辨率特殊？你们测试过吗，大神

**Comment by faceair** [comment]
没有测试过 iPhone X，我自己的是 6sp

**Comment by faceair** [comment]
手动在游戏界面截个图我看看吧

**Comment by HockeyWX** [comment]
![img_0483](https://user-images.githubusercontent.com/23329726/34465675-5ef5b706-eef2-11e7-8248-c1206d7853b9.PNG)

**Comment by faceair** [comment]
明白了，有个阈值要调一下

**Comment by HockeyWX** [comment]
好了告知下，谢谢

**Comment by faceair** [comment]
好的，现在正在加回测，好了一起发 等会跟你说

**Comment by faceair** [comment]
改好了，可以用最新版再试一下。我的手机上运行 WebDriverRunner 非常卡，你的卡吗？

**Comment by ColeXm** [comment]
我试一下，  不卡啊。。

**Comment by faceair** [comment]
👌可能是我这机型太老了。欢迎帮忙测下最新的自动系数调节，可以看下同目录的 jump.test.png 是否都截在方块刚好落地的瞬间

**Comment by ColeXm** [comment]
自动调节系数 怎么弄?

**Comment by faceair** [comment]
直接运行就行了，每次跳完会再截一个图验证刚才的跳跃距离和系数(也就是我刚才说的文件👆)，并把实际数据存储到 similar.ai 里，顺利的话跑一段时间后就跳的越来越准了

**Comment by ColeXm** [comment]
不行。。 就头两次 跳到100多分， 后面越来越不准。。系数2.0-2.5都试过了

**Comment by faceair** [comment]
我刚说的文件截图每次都是准的么？如果这个不准的话自动调节没法正常工作

**Comment by reilost** [comment]
[debugger.zip](https://github.com/faceair/youjumpijump/files/1595847/debugger.zip)
似乎兼容有点问题-  -

**Comment by faceair** [comment]
@reilost 定位没问题，每次都缺一点 自己加点系数吧，多试几次

**Comment by zuojinmin** [comment]
你可以用下我提交的试下，已经刷分到2000 了
https://github.com/zuojinmin/youjumpijump

**Comment by ColeXm** [comment]
@zuojinmin  怎么试， 你这里面貌似没有执行文件啊

**Comment by faceair** [comment]
最新版本已能正确识别 iPhone X 的长额头。
