### ISSUE TITLE
更小更轻快的Win一键包

### ISSUE THREAD

**Issue by tetsaicn** [faceair/youjumpijump#46]
[win一键包.zip](https://github.com/faceair/youjumpijump/files/1595782/win.zip)
当然驱动还得自己搞

**Comment by faceair** [comment]
非常感谢。你打包的这个版本对比当前的版本比有哪些改进呢？

**Comment by tetsaicn** [comment]
upx压缩并且减少了一堆没用文件，压缩包1Mb，对海外服务器github/大陆用户下载更加友好。
另外对文件名进行了改写，批处理分为 初次使用 启动 结束
分别可以 复制文件/启动adb并启动ai/结束adb

**Comment by lxk0301** [comment]
@tetsaicn 使用的是你这个包，运行后，cmd就如下图所示，是啥原因呢？
![snipaste_2018-01-02_10-01-49](https://user-images.githubusercontent.com/21308593/34472782-4e73454e-efa4-11e7-83d3-632e6b9d2dc1.png)

**Comment by NEIL-ORZZH** [comment]
@tetsaicn 请求一下你的源码可以开放吗，和楼主的好像不一样，使用你的很精确到中心点

**Comment by tetsaicn** [comment]
@lxk0301 这并不是我的，我的有三个cmd，也没有set
@Neils320 只是重新编译了并且upx压缩

**Comment by faceair** [comment]
👍 非常感谢！已采纳，最新版本 windows.zip 使用你提供的方式打包的。
