### ISSUE TITLE
iphone 7 用youjumpijump-ios 完全不准啊，跳到2分就挂了

### ISSUE THREAD

**Issue by 18o** [faceair/youjumpijump#47]

**Comment by faceair** [comment]
开始不准请手动调整初始参数使每次都跳到方块中心。也可以把 debugger 目录打包给我看看。

**Comment by 18o** [comment]
[debugger.zip](https://github.com/faceair/youjumpijump/files/1595884/debugger.zip)
用的默认2，开始两个还凑合，之后就完全偏了

**Comment by faceair** [comment]
没看到歪的厉害的图啊

**Comment by 18o** [comment]
看看这个诶，真的只有2分😢
[debugger.zip](https://github.com/faceair/youjumpijump/files/1595885/debugger.zip)

**Comment by mybolide** [comment]
15分 就不行了， iphone7， 6p， x都这样

**Comment by ftitreefly** [comment]
我测试了iPhone7，跑到300多分了，目前没有问题

**Comment by ghost** [comment]
[debug.log](https://github.com/faceair/youjumpijump/files/1596216/debug.log)
iphone 7p  跳了600分左右

**Comment by zuojinmin** [comment]
你可以用下我提交的试下，已经刷分到2000 了
https://github.com/zuojinmin/youjumpijump

**Comment by danplin** [comment]
@zuojinmin 用你这个编译好的也是不行哦。最多跳到第四步就完了。iPhone7 iOS11.1.2

**Comment by faceair** [comment]
优化了一下识别算法，可以再次尝试一下 我自己的 6sp 可以到 3k 多还没死（不过这个分数提交不上...）

**Comment by faceair** [comment]
没有回复的话这个 issue 先关了，有问题可以再带上 debugger 目录提 issue。
