### ISSUE TITLE
这是什么问题

### ISSUE THREAD

**Issue by zuojinmin** [faceair/youjumpijump#49]
MacBook-Pro:jump zuojinmin$ chmod 775 ./youjumpijump-ios.dms || true && ./youjumpijump-ios.dms
请输入 WebDriverAgentRunner 监听的 IP 和端口 (例如 192.168.9.94:8100):192.168.1.105:8100
请输入跳跃系数(推荐值 2，可适当调整):3.1
2018/01/01 20:52:34 illegal base64 data at input byte 2: goroutine 1 [running]:
runtime/debug.Stack(0xc420055b80, 0x127ff60, 0xc42011e090)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:56 +0x73
panic(0x127ff60, 0xc42011e090)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
main.screenshot(0xc4200163c0, 0x12, 0x1, 0x1, 0x0)
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:42 +0x2fe
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:82 +0x381
程序已崩溃，按任意键退出

**Comment by zuojinmin** [comment]
你用的 go是什么版本？ 我的是1.9

**Comment by zuojinmin** [comment]
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"

**Comment by faceair** [comment]
与 #41 重复，到那边讨论吧
