### ISSUE TITLE
iphone6p, 7, X跳不了几分就挂了

### ISSUE THREAD

**Issue by mybolide** [faceair/youjumpijump#50]
请看附件
[debugger.zip](https://github.com/faceair/youjumpijump/files/1596073/debugger.zip)

**Comment by zuojinmin** [comment]
你可以用下我提交的试下，已经刷分到2000 了
https://github.com/zuojinmin/youjumpijump

**Comment by poisonous6** [comment]
这东西咋用呢？完全不会用啊

**Comment by mybolide** [comment]
@zuojinmin 还不行，跳了6分

**Comment by faceair** [comment]
优化了一下识别算法，可以再次尝试一下 我自己的 6sp 可以到 3k 多还没死（不过这个分数提交不上...）

**Comment by faceair** [comment]
没有回复的话这个 issue 先关了，有问题可以再带上 debugger 目录提 issue。
