### ISSUE TITLE
小米mix2无法正常跳跃

### ISSUE THREAD

**Issue by elecxwr** [faceair/youjumpijump#51]
很奇怪，第一次跳了57分死了，之后分数基本个位数了。
程序距离判断正确，但是跳得总会偏前，感觉是按压时间不够。又不知道第一次怎么跳到57分的…
[debugger.zip](https://github.com/faceair/youjumpijump/files/1596078/debugger.zip)

**Comment by faceair** [comment]
😑有可能训练数据被污染了 `adb shell rm /data/local/tmp/similar.ai` 删一下，我刚也在想怎么清洗异常数据

**Comment by normallama** [comment]
确实是训练问题，同mix2删除以后分数明显高了很多，而且每次翻车都是出在有similar的时候，可能是分辨率不同导致训练数据的污染吧

**Comment by faceair** [comment]
到 #61 讨论吧。
