### ISSUE TITLE
特殊分辨率自动判断异常

### ISSUE THREAD

**Issue by normallama** [faceair/youjumpijump#52]
特殊分辨率下自动判断的参数不如手动调节的参数适合，如何关闭自动判断改为完全使用输入参数
设备为小米MIX2，分辨率为1080*2160

**Comment by faceair** [comment]
不支持，这个项目后面的目标是越来越傻瓜，会逐渐抛弃输入任何参数，包括现在的初始参数。最新的版本我刚加入了基于统计的自动跳跃系数判断，目前正在考虑相同分辨率的用户间共享训练数据。目前我们的算法上关键点的识别都是准的，主要问题是系数的变化规律还没有掌握。

**Comment by normallama** [comment]
好的，期待你的成果

**Comment by faceair** [comment]
😁
