### ISSUE TITLE
Samsung Note5问题

### ISSUE THREAD

**Issue by zhaoyifan1996** [faceair/youjumpijump#54]
2018/01/01 17:04:55 from:[224 734] to:[526 566] distance:345.58 similar:0.00 ratio:2.04 press:704.99ms 
2018/01/01 17:05:00 from:[529 741] to:[215 560] distance:362.43 similar:0.00 ratio:2.04 press:739.36ms 
2018/01/01 17:05:04 from:[256 722] to:[503 578] distance:285.91 similar:0.00 ratio:2.04 press:583.26ms 
2018/01/01 17:05:09 from:[211 743] to:[527 565] distance:362.68 similar:0.00 ratio:2.04 press:739.88ms 
2018/01/01 17:05:13 from:[495 720] to:[254 579] distance:279.22 similar:0.00 ratio:2.04 press:569.60ms 
2018/01/01 17:05:18 from:[514 723] to:[241 572] distance:311.98 similar:0.00 ratio:2.04 press:636.43ms 
2018/01/01 17:05:23 from:[206 747] to:[552 559] distance:393.78 similar:0.00 ratio:2.04 press:803.30ms 
2018/01/01 17:05:27 from:[272 708] to:[478 588] distance:238.40 similar:0.00 ratio:2.04 press:486.34ms 
2018/01/01 17:05:32 from:[471 705] to:[277 597] distance:222.04 similar:0.00 ratio:2.04 press:452.95ms 
2018/01/01 17:05:36 from:[501 717] to:[263 588] distance:270.71 similar:0.00 ratio:2.04 press:552.25ms 
2018/01/01 17:05:41 from:[215 754] to:[549 553] distance:389.82 similar:0.00 ratio:2.04 press:795.23ms 
2018/01/01 17:05:46 from:[445 693] to:[318 606] distance:153.94 similar:0.00 ratio:2.04 press:314.04ms 
2018/01/01 17:05:51 from:[501 720] to:[266 590] distance:268.56 similar:0.00 ratio:2.04 press:547.86ms 
2018/01/01 17:05:55 from:[183 758] to:[567 539] distance:442.06 similar:0.00 ratio:2.04 press:901.80ms 
2018/01/01 17:06:01 from:[253 718] to:[496 583] distance:277.98 similar:0.00 ratio:2.04 press:567.08ms 
2018/01/01 17:06:06 from:[181 760] to:[559 547] distance:433.88 similar:0.00 ratio:2.04 press:885.12ms 
2018/01/01 17:06:11 from:[546 744] to:[205 554] distance:390.36 similar:0.00 ratio:2.04 press:796.33ms 
2018/01/01 17:06:16 from:[512 729] to:[246 579] distance:305.38 similar:309.29 ratio:1.7317551680625647 press:528.84ms 
2018/01/01 17:06:21 from:[327 729] to:[470 598] distance:193.93 similar:0.00 ratio:2.04 press:395.62ms 
2018/01/01 17:06:26 from:[470 736] to:[257 585] distance:261.09 similar:0.00 ratio:2.04 press:532.63ms 
2018/01/01 17:06:32 from:[293 723] to:[480 592] distance:228.32 similar:0.00 ratio:2.04 press:465.77ms 
2018/01/01 17:06:37 from:[256 721] to:[475 596] distance:252.16 similar:0.00 ratio:2.04 press:514.41ms 
2018/01/01 17:06:43 from:[219 735] to:[519 570] distance:342.38 similar:344.51 ratio:1.7305192209330185 press:592.50ms 
2018/01/01 17:06:48 from:[460 690] to:[519 570] distance:133.72 similar:0.00 ratio:2.04 press:272.79ms 
2018/01/01 17:06:53 can't find the starting point，please export the debugger directory
![1514826406](https://user-images.githubusercontent.com/10597171/34469448-f37d9d96-ef59-11e7-88bd-fb97be959b0d.png)
![1514826411](https://user-images.githubusercontent.com/10597171/34469450-f62d764c-ef59-11e7-824e-7e2ebfb877d5.png)

**Comment by faceair** [comment]
你这是之前 1.15 版本自动系数调节的问题，那个没测好就放出来了.. 非常抱歉
可以下载最新版本再次尝试
