### ISSUE TITLE
华为mate9 pro 跳几下就死了

### ISSUE THREAD

**Issue by clj12081103** [faceair/youjumpijump#59]
系数2.04 跳几下就死了
试了其他系数，也一样
分辨率2560*1440
![](http://i2.bvimg.com/600646/ec3676194023a7d6.jpg)

**Comment by roceys** [comment]
许多这问题。。。

**Comment by clj12081103** [comment]
最高跳到两百多

**Comment by faceair** [comment]
这个图看不出来问题，请把 debugger 目录提交上来吧
