### ISSUE TITLE
最新版的报错

### ISSUE THREAD

**Issue by ishwy** [faceair/youjumpijump#6]
win10
执行 go run main.go
main.go:15:2: cannot find package "github.com/nfnt/resize" in any of:
        E:\go\src\github.com\nfnt\resize (from $GOROOT)
        C:\Users\shwy\go\src\github.com\nfnt\resize (from $GOPATH)

**Comment by faceair** [comment]
可以直接下载可执行文件。这个问题是因为代码没有正确放到 GOPATH 中，可以把代码放到 $GOPATH/src/github.com/faceair 下

**Comment by ishwy** [comment]
OK, 搞定了, 厉害了,
