### ISSUE TITLE
跳几下ratio值就被改动了，是不是微信那把这个值改了

### ISSUE THREAD

**Issue by italks** [faceair/youjumpijump#62]
/data/local/tmp $ ./youjumpijump-android                                                                 
input jump ratio (recommend 2.04):2.04
2018/01/02 03:22:05 from:[497 707] to:[267 600] distance:253.67 similar:0.00 ratio:2.04 press:517.49ms 
2018/01/02 03:22:09 from:[288 715] to:[476 595] distance:223.03 similar:0.00 ratio:2.04 press:454.99ms 
2018/01/02 03:22:13 from:[524 749] to:[212 559] distance:365.30 similar:372.73 ratio:1.6394901001149786 press:598.91ms 
2018/01/02 03:22:17 from:[286 702] to:[212 559] distance:161.01 similar:0.00 ratio:2.04 press:328.47ms 
2018/01/02 03:22:21 can't find the starting point，please export the debugger directory

**Comment by faceair** [comment]
没有数据证明按压时间跟距离成正比关系，所以这里是想本地基于统计分析出最合适的系数。目前可能有点 bug，临时的解决方案讨论可以参考 #61
