### ISSUE TITLE
锤子手机坚果pro跳几下就死了

### ISSUE THREAD

**Issue by Eddie-he** [faceair/youjumpijump#64]
最高跳过70分刚开始，后边一般都十几分就死了。

**Comment by faceair** [comment]
请带上 debugger 日志，怀疑是 #61 的问题，可以尝试下之前的版本。

**Comment by SE777ENL** [comment]
[debugger.zip](https://github.com/faceair/youjumpijump/files/1596875/debugger.zip)
锤子坚果Pro，最高跳151，通常都是几十这样子。已附上debugger。

**Comment by faceair** [comment]
受自动调节系数问题影响了，可以下之前的版本。可以到 #61 参与讨论。
