### ISSUE TITLE
是不是手机要Root才能用呢?我的手机是小米Mix2

### ISSUE THREAD

**Issue by libralm** [faceair/youjumpijump#67]
日志信息是这个：
2018/01/02 05:53:22 now jump ratio is 2.000000
2018/01/02 05:53:24 from:[476 757] to:[299 688] distance:189.97 ratio:2 press:379.95ms 
2018/01/02 05:53:25 touch failed: goroutine 1 [running]:
runtime/debug.Stack(0x10839df4, 0x207178, 0x26fcb8)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0x80
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/main.go:21 +0x40
panic(0x207178, 0x26fcb8)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/main.go:77 +0x7a4
2018/01/02 05:58:01 now jump ratio is 2.000000
2018/01/02 05:58:04 from:[476 757] to:[299 688] press:379ms
2018/01/02 05:58:04 signal: killed: goroutine 1 [running]:
runtime/debug.Stack(0x10b39d54, 0x115a90, 0x127b2010)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0x80
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:96 +0x40
panic(0x115a90, 0x127b2010)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:197 +0xf70
2018/01/02 06:01:28 now jump ratio is 2.000000
2018/01/02 06:01:30 from:[476 757] to:[299 688] press:379ms
2018/01/02 06:01:31 signal: killed: goroutine 1 [running]:
runtime/debug.Stack(0x10839d54, 0x115a90, 0x1080a020)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0x80
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:96 +0x40
panic(0x115a90, 0x1080a020)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:197 +0xf70
2018/01/02 06:05:31 now jump ratio is 2.000000
2018/01/02 06:05:33 can't find the starting point锛宲lease export the debugger directory
2018/01/02 06:05:43 now jump ratio is 2.040000
2018/01/02 06:05:45 from:[225 817] to:[526 646] press:706ms
2018/01/02 06:05:45 signal: killed: goroutine 1 [running]:
runtime/debug.Stack(0x10a39d54, 0x115a90, 0x10a92110)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0x80
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:96 +0x40
panic(0x115a90, 0x10a92110)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:197 +0xf70
2018/01/02 06:20:52 now jump ratio is 2.040000
2018/01/02 06:20:55 from:[225 817] to:[526 646] press:706ms
2018/01/02 06:20:56 signal: killed: goroutine 1 [running]:
runtime/debug.Stack(0x10d39d54, 0x115a90, 0x10d0a020)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0x80
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:96 +0x40
panic(0x115a90, 0x10d0a020)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:197 +0xf70
2018/01/02 06:23:43 now jump ratio is 2.040000
2018/01/02 06:23:44 from:[225 817] to:[526 646] press:706ms
2018/01/02 06:23:45 signal: killed: goroutine 1 [running]:
runtime/debug.Stack(0x12418d54, 0x115a90, 0x1080a0d0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0x80
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:96 +0x40
panic(0x115a90, 0x1080a0d0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:197 +0xf70

**Comment by mutulong** [comment]
我也刚在mix 2 试了，同样问题 -

`chiron:/data/local/tmp $ ./youjumpijump-android2                                                                                          
input jump ratio (recommend 2.04):2.04
2018/01/02 07:21:31 now jump ratio is 2.040000
2018/01/02 07:21:33 from:[225 867] to:[526 646] press:761ms
2018/01/02 07:21:34 signal: killed: goroutine 1 [running]:
runtime/debug.Stack(0x10939e4c, 0x2333e0, 0x109bd1b0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0x80
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/main.go:21 +0x40
panic(0x2333e0, 0x109bd1b0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/main.go:66 +0x534
the program has crashed, press any key to exit`

**Comment by faceair** [comment]
报错是截图命令执行失败，手动执行 `adb shell /system/bin/screencap -p /data/local/tmp/jump.png` 呢？

**Comment by libralm** [comment]
@mutulong @faceair 知道什么原因了，是因为没有开usb调试中的 安全设置模式，导致adb shell无法模拟触摸事件。

**Comment by faceair** [comment]
👌一般都是开发者选项的设置问题。
