### ISSUE TITLE
小米 mix2 死的太快

### ISSUE THREAD

**Issue by dongfengweixiao** [faceair/youjumpijump#68]
反馈请将 debugger 目录打包附上，Android 端可以通过 `adb pull /data/local/tmp/debugger` 拉下 debugger 目录。

在各种比例下的得分情况：
2.04  85
2.038 76

2.05 120
2.06 168
2.08 83
2.07 108

2.065 62
2.061 108

2.055 92

**Comment by faceair** [comment]
反馈请将 debugger 目录打包附上，Android 端可以通过 adb pull /data/local/tmp/debugger 拉下 debugger 目录。

**Comment by faceair** [comment]
https://github.com/faceair/youjumpijump/issues/18#issuecomment-354632426 可以试下 2.175，另外也可能是 #61 影响。

**Comment by mutulong** [comment]
2.21 到 720
