### ISSUE TITLE
感觉加了resize这个版本，目标定位不准了

### ISSUE THREAD

**Issue by 18o** [faceair/youjumpijump#7]
感觉加了resize这个版本，目标定位不准了，大部分调不到中心点上，而1.02版本还是跳到中心点的时候多

**Comment by MuJJus** [comment]
系数从 2.04 试到了 2.17 死活过不了 1000 分

**Comment by faceair** [comment]
欢迎带上定位不准截图，我来手动确认下

**Comment by edisonseven** [comment]
![jump](https://user-images.githubusercontent.com/16166512/34452325-d616e642-ed77-11e7-9b74-261afd138c7e.png)
定位确实不准，我最高才调到700多，然后就跳过头了

**Comment by MuJJus** [comment]
高分辨率强行 resize 可能丢失了细节就不准了，大的物体还行，400 以后连续小的就有点吃力了。

**Comment by faceair** [comment]
可能是长截屏定位不准的问题，刚才修了一波，欢迎下载最新版本再试。

**Comment by faceair** [comment]
新增了基于统计的自动系数调节，欢迎尝试。

**Comment by 18o** [comment]
刷太多次，被拉黑名单了 ~~
