### ISSUE TITLE
X 试了好多系数都跳不几次

### ISSUE THREAD

**Issue by xw0211** [faceair/youjumpijump#72]
[debugger.zip](https://github.com/faceair/youjumpijump/files/1597334/debugger.zip)

大神求修复呀～～～

**Comment by liasica** [comment]
我也是- -

**Comment by faceair** [comment]
X bug 已知最新代码已修，还没发版.. 略等一等..

**Comment by liasica** [comment]
@faceair 我自行编译是否可以？

**Comment by faceair** [comment]
已发版，欢迎再次尝试。
