### ISSUE TITLE
下载windows包后执行错误

### ISSUE THREAD

**Issue by yinzl07** [faceair/youjumpijump#76]
2018/01/02 14:40:32 now jump ratio is 1.000000
2018/01/02 14:40:33 unexpected EOF: goroutine 1 [running]:
runtime/debug.Stack(0x10639df4, 0x20b768, 0x1060c048)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0x80
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/main.go:21 +0x40
panic(0x20b768, 0x1060c048)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/main.go:58 +0x7bc

**Comment by faceair** [comment]
请带上完整 debugggr 目录，似乎是图片格式问题
