### ISSUE TITLE
iphone7p 程序已崩溃，按任意键退出

### ISSUE THREAD

**Issue by december7** [faceair/youjumpijump#77]
请输入 WebDriverAgentRunner 监听的 IP 和端口 (例如 192.168.9.94:8100):192.168.199.243:8100
请输入跳跃系数(推荐值 2，可适当调整):2.04
2018/01/02 23:24:08 现在跳跃系数是 2.040000
2018/01/02 23:24:38 Get http://192.168.199.243:8100/screenshot: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers): goroutine 1 [running]:
runtime/debug.Stack(0xc42004faf8, 0x128f740, 0xc4201140c0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:28 +0x73
panic(0x128f740, 0xc4201140c0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:57 +0xfcb
程序已崩溃，按任意键退出
[debug.log](https://github.com/faceair/youjumpijump/files/1597924/debug.log)

**Comment by faceair** [comment]
#71 同样的问题，到那边讨论吧
