### ISSUE TITLE
touch failed: goroutine 1

### ISSUE THREAD

**Issue by XxYyKk** [faceair/youjumpijump#79]
2018/01/03 02:42:08 now jump ratio is 2.500000
2018/01/03 02:42:10 from:[224 734] to:[526 566] distance:345.58 ratio:2.5 press:863.96ms 
2018/01/03 02:42:10 touch failed: goroutine 1 [running]:
runtime/debug.Stack(0x1251edf4, 0x207178, 0x26fcb8)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0x80
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/main.go:21 +0x40
panic(0x207178, 0x26fcb8)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/main.go:77 +0x7a4
the program has crashed, press any key to exitq
shell@nikel:/data/local/tmp $ exit

**Comment by XxYyKk** [comment]
请问一下这个是什么问题

**Comment by faceair** [comment]
开发者选项安全设置或模拟触摸确认一下

**Comment by xuyao91** [comment]
我也有这个问题，怎么解决？

**Comment by xuyao91** [comment]
解决了，在开发者中心，找到安全设置，打开就行
