### ISSUE TITLE
小米 5mi 的系数应该怎么调 感觉调2.14只能到·300多

### ISSUE THREAD

**Issue by UsingMisz** [faceair/youjumpijump#82]
反馈请将 debugger 目录打包附上，Android 端可以通过 `adb pull /data/local/tmp/debugger` 拉下 debugger 目录。

**Comment by sudami** [comment]
按照博主的这个算法，时间系数跟分辨率有关系：
1080以后的分辨率用2.04比较稳定，720的分辨率下得 > 2.11，需反复微调

**Comment by faceair** [comment]
其实并不一定是两位小数，可以写很多位的.. 自己再调整一下吧
