### ISSUE TITLE
白色圆柱判断错误

### ISSUE THREAD

**Issue by llgoer** [faceair/youjumpijump#85]
反馈请将 debugger 目录打包附上，Android 端可以通过 `adb pull /data/local/tmp/debugger` 拉下 debugger 目录。
[debugger.zip](https://github.com/faceair/youjumpijump/files/1600224/debugger.zip)

**Comment by faceair** [comment]
好像还缺日志  debug.log 文件呢？ 看起来不是识别错了，是系数不够精确

**Comment by name2008less** [comment]
@faceair  求编译新版本

**Comment by faceair** [comment]
@94oiio 目前还没到能发新版的程度，还在密集的调整中，如有需要可以自己改动后编译。Go 的编译还是挺简单的。
