### ISSUE TITLE
误删tmp文件夹导致无法push

### ISSUE THREAD

**Issue by haofeix** [faceair/youjumpijump#86]
我误删了tmp文件夹，现在无法push。在手机上操作手动创建tmp文件夹并将权限改成了rwxrwxrwx（777），拥有者和群组都是root，可是还是不能push.

**Comment by faceair** [comment]
错误日志是？

**Comment by haofeix** [comment]
permission denied remote couldn't create file
现在问题解决了 删除tmp时使用到了es文件管理器 似乎占用了root权限 导致不管push什么文件都denied
