### ISSUE TITLE
使用后记录不刷新，难道能识别辅助了？

### ISSUE THREAD

**Issue by chocolatesir** [faceair/youjumpijump#87]
之前使用过早期版本刷到2400分，周一刷新成绩为0后没有用外挂，一直自己玩，昨天用了外挂，267分，提示超过多少位好友，退出游戏后再看还是以前的分数，刚刚反复测试都是这样，不管用辅助多少分最后都不会真正保存记录，不知道是不是个例。

**Comment by chocolatesir** [comment]
刚刚用最新的客户端试了又正常了。。真的搞不懂了

**Comment by faceair** [comment]
可能是本机的排行榜缓存了，可以去其他手机上确认下。

**Comment by CoMList** [comment]
我刷了1000多分，没过一会儿就没了，只剩手打的分数

在 2018-01-04 00:05:33，chocolatesir <notifications@github.com> 写道：


之前使用过早期版本刷到2400分，周一刷新成绩为0后没有用外挂，一直自己玩，昨天用了外挂，267分，提示超过多少位好友，退出游戏后再看还是以前的分数，刚刚反复测试都是这样，不管用辅助多少分最后都不会真正保存记录，不知道是不是个例。
