### ISSUE TITLE
用模拟器执行会发生 unexpected newline错误

### ISSUE THREAD

**Issue by yerikyy** [faceair/youjumpijump#88]
因为没有安卓机所以使用了夜深模拟器进行测试。
debugger文件只有一句话

> 2018/01/03 20:52:34 unexpected newline

  
![capture](https://user-images.githubusercontent.com/19756219/34539796-e9b1c7fa-f086-11e7-8349-efa72bbd50d9.PNG)

**Comment by faceair** [comment]
输入 2.04 回车
