### ISSUE TITLE
Mac-iOS, 运行不了 .dms格式文件

### ISSUE THREAD

**Issue by sunyuzheng** [faceair/youjumpijump#89]
无论是直接点开，还是在terminal里面用chmod 775 ./youjumpijump-ios || true && ./youjumpijump-ios，都打不开。是我需要先安装什么环境吗？

**Comment by faceair** [comment]
错误日志是？

**Comment by titi14gj** [comment]
chmod 775 ./youjumpijump-ios.dms || true && ./youjumpijump-ios.dms

**Comment by sunyuzheng** [comment]
加了 .dms也不行呀，就说command not found。分开先运行chmod 775 在打文件名，也是不行

**Comment by faceair** [comment]
`cd ~/Downloads` 再执行
