### ISSUE TITLE
兄弟，自动跳跃系数什么时候有出来呢？

### ISSUE THREAD

**Issue by libralm** [faceair/youjumpijump#90]
您好，兄弟，自动跳跃系数什么时候有出来呢？我用小米mix，试过好多参数了，但是呢，跳不过300

**Comment by faceair** [comment]
#61 正在想办法

**Comment by sudami** [comment]
@faceair 博主，我这里测试了，在1080P以上的机器，跑1000~2000多分都很稳定。
只有在分辨率是720P的机器下，需要自动修正系数。

你那个修正算法我研读理解后移植成android JAVA里面跑了，确实不稳定，没多少步就会用修正后的系数*距离，得到一个不合理的时长，然后就挂了..

**Comment by cherryxyz** [comment]
我用的是小米max2,跑不出来。想问一下。能否加个QQ层主？

**Comment by faceair** [comment]
@sudami 在不用系数修正时，我的 720p 机器能上 8000 多分，上了自动调整系数后能上 1.7w 分还不死

正在重写识别算法，目前已有思路重新加上自动调整参数了，等我写 demo 验证下可行性。

也可以到 #61 继续讨论
