### ISSUE TITLE
兄弟，我用这个跳了1000多，第二天排名就没了，有bug！！！

### ISSUE THREAD

**Issue by jerardq** [faceair/youjumpijump#91]
反馈请将 debugger 目录打包附上，Android 端可以通过 `adb pull /data/local/tmp/debugger` 拉下 debugger 目录。

**Comment by UsingMisz** [comment]
突然跳那么多会被检测到 每次增加个200就差不多了

**Comment by cherryxyz** [comment]
能不能加个QQ,我这个运行不出来。想问问

**Comment by UsingMisz** [comment]
747608835@qq.com

**Comment by jerardq** [comment]
按照帖子一步一步来，有什么问题在这里讨论，其他人也可以看到

**Comment by jerardq** [comment]
需要在 Mac 上安装配置 WebDriverAgent，参考教程

**Comment by jerardq** [comment]
https://testerhome.com/topics/7220

**Comment by cherryxyz** [comment]
我的是小米max2,没有root，已经开了usb调试了。然后文件没法push到手机里。报错：couldn't create file : permission denied

**Comment by jerardq** [comment]
我试验的iphone，andriod没试过呢，建议你新开个issue

**Comment by faceair** [comment]
反作弊可以到 #74 讨论
