### ISSUE TITLE
小米5  2.3系数只有四百多 大家有什么更好的数据吗？

### ISSUE THREAD

**Issue by UsingMisz** [faceair/youjumpijump#92]
反馈请将 debugger 目录打包附上，Android 端可以通过 `adb pull /data/local/tmp/debugger` 拉下 debugger 目录。

**Comment by RojerAlone** [comment]
2.2 只有 200 多分

**Comment by 2659494286** [comment]
默认2.04就挺好啊 我1300多分 5.2手机屏

**Comment by faceair** [comment]
如果每次都不能跳到中心点可以自己微调下系数。
