### ISSUE TITLE
关于adb push 文件到手机中的问题

### ISSUE THREAD

**Issue by cherryxyz** [faceair/youjumpijump#93]
youjumpijump-android 文件一定要放到手机data/local/tmp目录下吗？我手机小米2，没root。文件管理里面只有data目录。里面没有local。我手动创建local/tmp之后。电脑里面只能看到local这一层目录。里面什么都没有。没有看到tmp文件。。。不知道这是什么情况

**Comment by cherryxyz** [comment]
我手动把文件加到手机里了。试了下参数，2.04就10步。2.3有380步。不知道大家的系数是多少。

**Comment by faceair** [comment]
既然你解决了 issue 就先关了
