### ISSUE TITLE
mac, iPhone 7 Plus,  iOS 11.2.1,Client.Timeout exceeded while awaiting headers): goroutine 1 [running]:

### ISSUE THREAD

**Issue by yuankaiJGH** [faceair/youjumpijump#94]
这是啥

请输入跳跃系数(推荐值 2，可适当调整):2.04
2018/01/04 11:37:11 现在跳跃系数是 2.040000
2018/01/04 11:37:41 Get http://192.168.0.118:8100/screenshot: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers): goroutine 1 [running]:
runtime/debug.Stack(0xc42004baf8, 0x128f740, 0xc420079080)
	[/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24](url
[debugger.zip](https://github.com/faceair/youjumpijump/files/1602372/debugger.zip)
) +0xa7
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:28 +0x73
panic(0x128f740, 0xc420079080)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:57 +0xfcb
程序已崩溃，按任意键退出

**Comment by jerardq** [comment]
我用iproxy解决这个问题的，用了iproxy 连接地址改成127.0.0.1:8100

**Comment by faceair** [comment]
可以到 #71 讨论
