### ISSUE TITLE
无法上次数据

### ISSUE THREAD

**Issue by brightchain** [faceair/youjumpijump#95]
是被微信封杀了吗？无法上传数据

**Comment by c1ngular** [comment]
android能用，但是好友的排行上不显示我的分数了～

**Comment by Reteyery** [comment]
我昨天刷了2200 1650都没问题，今天刷了6000也是上传不上去，不知道是不是限制了分数，你刷了多少

**Comment by zomin** [comment]
115分 无法上传分数

**Comment by Reteyery** [comment]
@zomin 这么背...

**Comment by c1ngular** [comment]
同楼上，今天提示，无法上传分数了～昨天刷的分数微信好友都看不到了！

**Comment by walkerzhao** [comment]
是不是检测屏幕触碰了？

**Comment by zhukejin** [comment]
同上无法上传分数，但是同事的 iphone 6s 就可以上传。
除了系统不同，其他完全相同。
 另外，实验了几次，145 以下是可以上传成功的。

**Comment by faceair** [comment]
反作弊可以到 #74 讨论
