### ISSUE TITLE
Mac+iOS看错误日志，这是为啥

### ISSUE THREAD

**Issue by LeeFengHY** [faceair/youjumpijump#98]
Get http://192.168.1.46:8100/screenshot: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers): goroutine 1 [running]:
runtime/debug.Stack(0xc42004baf8, 0x128f740, 0xc420079080)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:28 +0x73
panic(0x128f740, 0xc420079080)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:57 +0xfcb

**Comment by faceair** [comment]
可以到 #71 讨论
