### ISSUE TITLE
Panic 退出

### ISSUE THREAD

**Issue by Aegeaner** [faceair/youjumpijump#99]
input jump ratio (recommend 2.04):2.04
2018/01/04 07:07:30 now jump ratio is 2.040000
2018/01/04 07:07:32 from:[225 817] to:[526 646] distance:346.18 ratio:2.04 press:706.21ms 
2018/01/04 07:07:33 touch failed: goroutine 1 [running]:
runtime/debug.Stack(0x12a34df4, 0x207178, 0x26fcb8)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0x80
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/main.go:21 +0x40
panic(0x207178, 0x26fcb8)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/main.go:77 +0x7a4
the program has crashed, press any key to exit

**Comment by faceair** [comment]
开发者选项，模拟触摸或相关安全选项是否打开？

**Comment by Aegeaner** [comment]
开发者选项里没找到模拟触摸

**Comment by Aegeaner** [comment]
可以了，谢谢。
